# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'
use_frameworks!
target 'ReadTime' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReadTime
 
 pod 'AFNetworking','~>3.0.4'
# pod 'SDWebImage', '~>3.8'
# pod 'SVProgressHUD','~> 2.0.4'
 pod 'UITableView+FDTemplateLayoutCell'
 pod 'MJRefresh'
 pod 'MJExtension'
# pod 'WordPress-iOS-Editor-Extension', :path => '../'
 pod 'WordPress-Editor-iOS-Extension'
#pod 'WordPress-Editor-iOS-Extension', :path => '../'
# U-Share SDK UI模块（分享面板，建议添加）
pod ‘UMengUShare/UI’

# 集成微信(精简版0.2M)
pod ‘UMengUShare/Social/ReducedWeChat'


# 集成QQ(精简版0.5M)
pod ‘UMengUShare/Social/ReducedQQ'


# 集成新浪微博(精简版1M)
pod ‘UMengUShare/Social/ReducedSina'


end
